### ISSUE TITLE
Extracting function for service.

### ISSUE THREAD

**Issue by alishir** [fafhrd91/actix-http#8]
I tried to refactor the `echo` example and extracting main code to a function, but I couldn't compile the code, because I couldn't set the function return type properly.

following is the code and the error:
```rust
fn handle_request(_req: Request) // ->  ???????
{
    _req.body()
        .limit(512)
        .and_then(|bytes: Bytes| {
            info!("request body: {:?}", bytes);
            let mut res = Response::Ok();
            res.header("x-head", HeaderValue::from_static("dummy value!"));
            Ok(res.body(bytes))
        })
}

```
and the error is `expected (), found struct futures::AndThen`. What should be the `handle_request` return type?

**Comment by fafhrd91** [comment]
You should play with `impl Future`

**Comment by alishir** [comment]
Thanks a lot, it works now.
